<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-jiangxm" name="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest" tests="40" failures="1" timestamp="15 Dec 2017 06:16:36 GMT" time="20.469" errors="1">
  <testcase name="test1" time="0.888" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.487" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.255" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.255" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.304" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.533" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.886" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.251" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="1.259" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest.test1(SecuredPayConfirmTest.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.288" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.295" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.267" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="securedPayConfirm" time="0.448" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.tools.dataprovider.ExcelProvider.next(ExcelProvider.java:188)
	at com.tools.dataprovider.ExcelProvider.next(ExcelProvider.java:1)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1118)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- securedPayConfirm -->
  <testcase name="test1" time="0.266" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.173" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.452" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.328" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="2.825" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.245" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.362" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.238" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.334" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.334" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.498" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.477" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.335" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.994" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.282" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.332" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.292" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.225" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.198" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="2.694" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.313" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.249" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.364" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.276" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.276" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.223" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
  <testcase name="test1" time="0.468" classname="com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest"/>
</testsuite> <!-- com.llwallet.interfaces.test.api.test.personal.SecuredPayConfirmTest -->
